import { test, expect } from '@playwright/test';

test('API validation using Playwright request', async ({ request }) => {

    // =========================
    // GET REQUEST
    // =========================

    const getResponse = await request.get(
        'https://jsonplaceholder.typicode.com/posts/1'
    );

    // Verify HTTP status
    expect(getResponse.status()).toBe(200);

    // Verify response is successful
    expect(getResponse.ok()).toBeTruthy();

    // Parse response JSON
    const getData = await getResponse.json();

    // Verify response structure
    expect(getData).toHaveProperty('id');
    expect(getData).toHaveProperty('title');
    expect(getData).toHaveProperty('body');
    expect(getData).toHaveProperty('userId');

    // Verify specific value
    expect(getData.id).toBe(1);

    // =========================
    // POST REQUEST
    // =========================

    const postResponse = await request.post(
        'https://jsonplaceholder.typicode.com/posts',
        {
            data: {
                title: 'Playwright API Test',
                body: 'Testing POST API using Playwright',
                userId: 1
            }
        }
    );

    // Verify POST status
    expect(postResponse.status()).toBe(201);

    expect(postResponse.ok()).toBeTruthy();

    // Parse POST response
    const postData = await postResponse.json();

    // Verify returned data
    expect(postData.title).toBe(
        'Playwright API Test'
    );

    expect(postData.body).toBe(
        'Testing POST API using Playwright'
    );

    expect(postData.userId).toBe(1);

    // ID should be generated by the API
    expect(postData).toHaveProperty('id');
});